services:
    # Menu Root
    msi_admin_menu_root_admin:
        class: %msi_admin.menu_root.admin%
        arguments: [ @msi_admin.menu_root_manager ]
        parent: msi_admin.admin
        tags:
            - { name: msi.admin }
        calls:
            - [ addChild, [ @msi_admin_menu_node_admin ] ]

    msi_admin.menu_root_manager:
        class: Msi\AdminBundle\Manager\MenuManager
        arguments: [ %msi_admin.menu.class% ]
        parent: msi_admin.manager

    # Menu Node
    msi_admin_menu_node_admin:
        class: %msi_admin.menu_node.admin%
        arguments: [ @msi_admin.menu_node_manager ]
        parent: msi_admin.admin
        tags:
            - { name: msi.admin }
        calls:
            - [ setParent, [ @msi_admin_menu_root_admin ] ]

    msi_admin.menu_node_manager:
        class: %msi_admin.manager.class%
        arguments: [ %msi_admin.menu.class% ]
        parent: msi_admin.manager

    # Page
    msi_admin_page_admin:
        class: %msi_admin.page.admin%
        arguments: [ @msi_admin.page_manager ]
        parent: msi_admin.admin
        tags:
            - { name: msi.admin }
        calls:
            - [addChild, [@msi_admin_block_admin]]

    msi_admin.page_manager:
        class: Msi\AdminBundle\Manager\PageManager
        arguments: [ %msi_admin.page.class% ]
        parent: msi_admin.manager

    # Block
    msi_admin_block_admin:
        class: %msi_admin.block.admin%
        arguments: [ @msi_admin.page_block_manager ]
        parent: msi_admin.admin
        tags:
            - { name: msi.admin }
        calls:
            - [setParent, [@msi_admin_page_admin]]

    msi_admin.page_block_manager:
        class: %msi_admin.manager.class%
        arguments: [ %msi_admin.block.class% ]
        parent: msi_admin.manager

    # Site
    msi_admin_site_admin:
        class: %msi_admin.site.admin%
        arguments: [ @msi_admin.site_manager ]
        parent: msi_admin.admin
        tags:
            - { name: msi.admin }

    msi_admin.site_manager:
        class: %msi_admin.manager.class%
        arguments: [ %msi_admin.site.class% ]
        parent: msi_admin.manager
